question_data = [
    {"text": "O Sol é uma estrela.", "answer": "V"},
    {"text": "A Lua é maior que o Sol.", "answer": "F"},
    {"text": "Existem sete continentes no mundo.", "answer": "V"},
    {"text": "A baleia-azul é o maior animal do planeta.", "answer": "V"},
    {"text": "O Brasil faz fronteira com 10 países.", "answer": "V"},
    {"text": "A água ferve a 90°C.", "answer": "F"},
    {"text": "O monte Everest é a montanha mais alta do mundo.", "answer": "V"},
    {"text": "Existem 24 horas em um dia.", "answer": "V"},
    {"text": "O ser humano tem cinco sentidos.", "answer": "V"},
    {"text": "O sangue humano é azul dentro do corpo.", "answer": "F"},
    {"text": "A Terra é o terceiro planeta do Sistema Solar.", "answer": "V"},
    {"text": "Os morcegos são cegos.", "answer": "F"},
    {"text": "O canguru é nativo da Austrália.", "answer": "V"},
    {"text": "O kiwi é uma fruta e também um pássaro.", "answer": "V"},
    {"text": "A capital do Japão é Tóquio.", "answer": "V"},
    {"text": "O corpo humano tem mais de 600 músculos.", "answer": "V"},
    {"text": "O tubarão é um mamífero.", "answer": "F"},
    {"text": "O cubo tem 12 arestas.", "answer": "V"},
    {"text": "O símbolo químico do ouro é Au.", "answer": "V"},
    {"text": "O chocolate é feito a partir de sementes de cacau.", "answer": "V"},
    {"text": "A fênix é uma ave real que existe na natureza.", "answer": "F"},
    {"text": "O menor país do mundo é o Vaticano.", "answer": "V"},
    {"text": "A Grande Muralha da China é visível da Lua.", "answer": "F"},
    {"text": "O Brasil foi descoberto em 1500.", "answer": "V"},
    {"text": "Os humanos podem sobreviver sem água por uma semana.", "answer": "F"},
    {"text": "As cobras podem sentir cheiro com a língua.", "answer": "V"},
    {"text": "A luz viaja mais rápido que o som.", "answer": "V"},
    {"text": "O Nilo é o maior rio do mundo.", "answer": "V"},
    {"text": "Os crocodilos podem viver até 100 anos.", "answer": "V"},
    {"text": "O número π (pi) é finito.", "answer": "F"},
    {"text": "O cavalo-marinho é o único animal em que o macho dá à luz.", "answer": "V"},
    {"text": "A eletricidade foi descoberta por Albert Einstein.", "answer": "F"},
    {"text": "A Rússia é o maior país do mundo em extensão territorial.", "answer": "V"},
    {"text": "A Antártida é o continente mais frio da Terra.", "answer": "V"},
    {"text": "O ser humano tem 4 tipos diferentes de dentes.", "answer": "V"},
    {"text": "O Brasil é o maior produtor mundial de café.", "answer": "V"},
    {"text": "A Grécia Antiga é considerada o berço da democracia.", "answer": "V"},
    {"text": "O triângulo equilátero tem três lados iguais.", "answer": "V"},
    {"text": "Saturno é conhecido pelos seus anéis.", "answer": "V"},
    {"text": "A capital da Austrália é Sydney.", "answer": "F"},
    {"text": "Os seres humanos possuem 206 ossos no corpo.", "answer": "V"},
    {"text": "A Estátua da Liberdade foi um presente da França para os EUA.", "answer": "V"},
    {"text": "O oceano Atlântico é o maior do mundo.", "answer": "F"},
    {"text": "As girafas têm a mesma quantidade de vértebras no pescoço que os humanos.", "answer": "V"},
    {"text": "O oxigênio compõe aproximadamente 21% da atmosfera da Terra.", "answer": "V"},
    {"text": "O DNA humano é idêntico em 99,9% entre todas as pessoas.", "answer": "V"},
    {"text": "A Terra completa uma volta ao redor do Sol em 365 dias.", "answer": "V"},
    {"text": "Os coalas são marsupiais.", "answer": "V"},
    {"text": "O corpo humano possui cinco pares de costelas.", "answer": "F"},
    {"text": "Na Califórnia, EUA, você não pode usar botas de cowboy a menos que tenha pelo menos duas vacas.", "answer": "V"}
]
